config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :sessions

  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  # Tell rails to encrypt the password in
  # password_digest column.
  has_secure_password
  # It also checks password == password_confirmation
  # when saving
  # Also provides the @user.authenticate() method
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # Provide a global current_user() method to
  # check if there's a user logged in from
  # any controller or view
  def current_user
    if session[:user_id]
      # If current user is set in the session
      # return the current user
      @current_user ||= User.find(session[:user_id])
    end
  end

  # Indicate that the current_user() should be
  # a helper (accessible from views)
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Check if user with email exists
    user = User.find_by_email(params[:email])
    if user &&user.authenticate(params[:password])
      # Password is correct
      # Set the session to current user
      # Will use cookie
      session[:user_id] = user.id

      redirect_to root_url
    else
      # There's no user or the password is incorrect
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save # will check password confirmation
      # User has been created
      # Log them in automatically
      session[:user_id] = @user.id
      redirect_to root_url
    else
      # There's been an error
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
          :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Userauth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Register</h1>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= form_for @user do |f| %>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>

    <p>
      <%= f.submit "Register" %>
    </p>
  <% end %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>
  <% if current_user %>
    Welcome, <%= current_user.email %>!

    Log out <%= link_to "here", logout_path %>

  <% else %>

    Log in <%= link_to "here", new_session_path %> or
    <%= link_to "register", new_user_path %>

  <% end %>
</p>